###查询
GET http://127.0.0.1:8080/api/user/?page=1&limit=20 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiTmFtZSI6IjE1NjMxMTc3MzQ1IiwiZXhwIjoxNjg2MzM4ODk2fQ.-CD8qe8MyXzo4w5Ob3FgRV0cBDHjQyg4c-j2Pl2Ynb0



###获取单个
GET http://127.0.0.1:8080/api/user/1/ HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiTmFtZSI6IjE1NjMxMTc3MzQ1IiwiZXhwIjoxNjg2MzM4ODk2fQ.-CD8qe8MyXzo4w5Ob3FgRV0cBDHjQyg4c-j2Pl2Ynb0


###更新
PUT http://127.0.0.1:8080/api/user/10/  HTTP/1.1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiTmFtZSI6IjE1NjMxMTc3MzQ1IiwiZXhwIjoxNjg2MzM4ODk2fQ.-CD8qe8MyXzo4w5Ob3FgRV0cBDHjQyg4c-j2Pl2Ynb0

{
    "name": "zcpp63636"
}

###创建
POST  http://127.0.0.1:8080/api/user/  HTTP/1.1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiTmFtZSI6IjE1NjMxMTc3MzQ1IiwiZXhwIjoxNjg2MzM4ODk2fQ.-CD8qe8MyXzo4w5Ob3FgRV0cBDHjQyg4c-j2Pl2Ynb0

{
    "name": "zcc",
    "age": 26,
    "username": "1sdszsssz2kakkkkss0ggsz361",
    "role": [1,2,3]
    "role2": [1,2,3]
}


###创建
POST  http://127.0.0.1:8080/api/menu/  HTTP/1.1
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiTmFtZSI6IjE1NjMxMTc3MzQ1IiwiZXhwIjoxNjg2MzM4ODk2fQ.-CD8qe8MyXzo4w5Ob3FgRV0cBDHjQyg4c-j2Pl2Ynb0

{
    "name": "zcc",
    "age": 26
}

###登陆
POST http://127.0.0.1:8080/api/login/  HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=dassssdz&password=zxcvbnmzx


###文件上传
POST http://127.0.0.1:8080/api/upload/  HTTP/1.1
Content-Type: multipart/form-data ;boundary=fileboundary

--fileboundary
Content-Disposition: form-data; name="file"; filename="a.mp4"

< "D:\下载\bandicam 2023-04-04 19-08-42-408.mp4"
--fileboundary--
