# Generated by Django 4.1.1 on 2023-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.JSONField(default=list, help_text='文件', null=True, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.JSONField(default=list, help_text='链接', null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.IntegerField(help_text='标签', null=True, verbose_name='标签'),
        ),
    ]
