# Generated by Django 4.1.1 on 2023-01-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='Area',
        ),
    ]
