# Generated by Django 4.1.1 on 2023-01-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_area_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='createAt',
        ),
        migrations.RemoveField(
            model_name='area',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='area',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='area',
            name='updateAt',
        ),
    ]
