# Generated by Django 4.1.1 on 2023-03-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_article_file_alter_article_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('dept_belong', models.IntegerField(blank=True, help_text='所属部门id', null=True)),
                ('creator', models.IntegerField(blank=True, help_text='创建人id', null=True)),
                ('name', models.CharField(help_text='规则名称-', max_length=50)),
                ('allowed_domains', models.CharField(blank=True, help_text='域名列表(逗号分隔)', max_length=800, null=True)),
                ('start_urls', models.CharField(blank=True, help_text='开始页(逗号分隔)', max_length=200, null=True)),
                ('start_page_num', models.IntegerField(blank=True, help_text='分页页数开头', null=True)),
                ('re_page_num', models.CharField(blank=True, help_text='分页页数正则', max_length=200, null=True)),
                ('page_format', models.CharField(blank=True, help_text='分页链接格式化字符', max_length=200, null=True)),
                ('page_format_shift', models.CharField(blank=True, help_text='分页链接页码转换(传入num判断并修改)', max_length=200, null=True)),
                ('re_page', models.CharField(blank=True, help_text='分页链接正则', max_length=200, null=True)),
                ('re_item', models.CharField(blank=True, help_text='内容链接正则', max_length=200, null=True)),
                ('xpath_page_restrict', models.CharField(blank=True, help_text='分页链接提取区域xpath', max_length=200, null=True)),
                ('xpath_item_restrict', models.CharField(blank=True, help_text='内容链接提取区域xpath', max_length=200, null=True)),
                ('xpath_name', models.CharField(blank=True, help_text='标题xpath', max_length=200, null=True)),
                ('xpath_time', models.CharField(blank=True, help_text='时间xpath', max_length=200, null=True)),
                ('re_time', models.CharField(blank=True, help_text='时间正则', max_length=200, null=True)),
                ('xpath_cover', models.CharField(blank=True, help_text='封面xpath', max_length=200, null=True)),
                ('xpath_content', models.CharField(blank=True, help_text='内容xpath', max_length=200, null=True)),
                ('xpath_source', models.CharField(blank=True, help_text='来源xpath', max_length=200, null=True)),
                ('re_source', models.CharField(blank=True, help_text='来源正则', max_length=200, null=True)),
                ('enable', models.BooleanField(default=True, help_text='是否启用')),
                ('category', models.IntegerField(blank=True, help_text='类型', null=True)),
            ],
            options={
                'verbose_name': '爬虫规则表',
                'db_table': 'spider',
            },
        ),
    ]
