# Generated by Django 4.1.1 on 2023-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_spider'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(blank=True, help_text='抓取文章发布时间', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, '发布'), (2, '抓取')], default=1, help_text='文章类型(1 发布, 2 抓取)'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, help_text='文章链接', max_length=100, null=True, verbose_name='文章链接'),
        ),
        migrations.AddField(
            model_name='article',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
