# Generated by Django 4.1.1 on 2023-01-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_area_createat_remove_area_dept_belong_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='menuinterface',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
    ]
