# Generated by Django 4.1.1 on 2023-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_article_pub_time_article_type_article_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='link',
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(help_text='来源', max_length=200, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(blank=True, help_text='抓取文章的发布时间', null=True),
        ),
    ]
