# Generated by Django 4.1.1 on 2023-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_remove_enterprise_is_delete_remove_file_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='file',
            field=models.JSONField(default=list, help_text='文件'),
        ),
    ]
