# Generated by Django 4.1.1 on 2023-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_enterprise_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='file',
            field=models.JSONField(default='[]', help_text='文件'),
        ),
    ]
