# Generated by Django 4.1.1 on 2023-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_enterprise_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='image',
            field=models.JSONField(default='[]', help_text='图片'),
        ),
    ]
