# Generated by Django 4.2.4 on 2023-10-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_user_name_alter_article_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': '用户信息'},
        ),
        migrations.AlterModelTableComment(
            name='user_info',
            table_comment='用户信息',
        ),
        migrations.AlterModelTable(
            name='user_info',
            table='user_info',
        ),
    ]
