# Generated by Django 4.1.1 on 2023-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_enterprise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(help_text='微信openid', max_length=100, null=True),
        ),
    ]
