# Generated by Django 4.1.1 on 2023-01-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_user_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='image2',
            field=models.JSONField(default=list, help_text='图片'),
        ),
    ]
