# Generated by Django 4.1.1 on 2023-01-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_enterprise_file_alter_enterprise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='image2',
        ),
    ]
