# Generated by Django 4.1.1 on 2023-01-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_user_ype_alter_user_openid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ype',
            new_name='type',
        ),
    ]
