# Generated by Django 4.1.1 on 2023-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_rename_ype_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='dept',
            name='dept_belong_id',
            field=models.IntegerField(blank=True, help_text='所属部门id', null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='menuinterface',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='creator_id',
            field=models.IntegerField(blank=True, help_text='创建人id', null=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='updateAt',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True),
        ),
    ]
