# Generated by Django 4.1.1 on 2023-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_dept_creator_id_dept_dept_belong_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='dept',
        ),
    ]
