# Generated by Django 4.2.4 on 2023-10-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_interface_menu_interface_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='model_name',
            field=models.CharField(db_comment='接口模型名称', default='a', max_length=100),
            preserve_default=False,
        ),
    ]
