# Generated by Django 4.2.4 on 2023-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_interface_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='max_page_num',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='page_format',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='page_format_shift',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='re_page_num',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='start_page_num',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_content',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_cover',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_item_restrict',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_name',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_page_restrict',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_source',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='xpath_time',
        ),
        migrations.AddField(
            model_name='spider',
            name='get_item',
            field=models.CharField(blank=True, db_comment='内容提取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='get_page',
            field=models.CharField(blank=True, db_comment='分页提取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='page_max',
            field=models.IntegerField(blank=True, db_comment='页数最大值', null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='page_min',
            field=models.IntegerField(blank=True, db_comment='页数最小值', null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='page_shift',
            field=models.CharField(blank=True, db_comment='页码转换', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='path_area',
            field=models.CharField(blank=True, db_comment='地点获取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='path_content',
            field=models.CharField(blank=True, db_comment='文章获取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='path_name',
            field=models.CharField(blank=True, db_comment='标题获取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='path_source',
            field=models.CharField(blank=True, db_comment='来源获取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='path_time',
            field=models.CharField(blank=True, db_comment='时间获取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='re_area',
            field=models.CharField(blank=True, db_comment='地点提取', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spider',
            name='type',
            field=models.IntegerField(choices=[(1, '普通分页爬虫'), (2, 'json分页爬虫')], db_comment='类型', default=1),
        ),
        migrations.AlterField(
            model_name='spider',
            name='re_item',
            field=models.CharField(blank=True, db_comment='内容过滤', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='re_page',
            field=models.CharField(blank=True, db_comment='分页过滤', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='re_source',
            field=models.CharField(blank=True, db_comment='来源提取', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spider',
            name='re_time',
            field=models.CharField(blank=True, db_comment='时间提取', max_length=200, null=True),
        ),
    ]
