# Generated by Django 4.2.4 on 2023-10-18 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_user_email_remove_user_phone_article_collect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_info',
        ),
        migrations.AddField(
            model_name='user_info',
            name='birthday',
            field=models.DateField(db_comment='生日', null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='icon',
            field=models.CharField(db_comment='头像', max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='signature',
            field=models.CharField(db_comment='个性签名', max_length=100, null=True, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user',
            field=models.OneToOneField(db_comment='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
