# Generated by Django 4.2.4 on 2023-10-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_user_info_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider',
            name='path_area',
        ),
        migrations.RemoveField(
            model_name='spider',
            name='re_area',
        ),
    ]
