# Generated by Django 4.2.4 on 2023-10-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_spider_path_area_remove_spider_re_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='creator',
            field=models.IntegerField(blank=True, db_comment='创建人id', null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='dept_belong',
            field=models.IntegerField(blank=True, db_comment='所属部门id', null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', null=True),
        ),
    ]
