# Generated by Django 4.2.4 on 2023-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_user_info_create_time_user_info_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], db_comment='性别', default=0, null=True, verbose_name='性别'),
        ),
    ]
