# Generated by Django 4.2.6 on 2023-10-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_root',
            field=models.CharField(db_comment='基础来源', max_length=200, null=True, verbose_name='基础来源'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_sub',
            field=models.CharField(db_comment='子版块', max_length=200, null=True, verbose_name='子版块'),
        ),
    ]
