# Generated by Django 4.2.6 on 2023-10-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_article_source_root_article_source_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.JSONField(db_comment='图片', default=list, null=True, verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.JSONField(db_comment='视频', default=list, null=True, verbose_name='视频'),
        ),
    ]
