# Generated by Django 4.2.6 on 2023-10-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_article_image_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(db_comment='作者', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='system.user_info', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, '图片'), (2, '视频'), (3, '文字')], db_comment='文章类型(1 图片, 2 视频, 3文字)', default=1),
        ),
    ]
